# Generated by Django 2.2.7 on 2019-11-06 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_auto_20191106_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
    ]
