# Generated by Django 2.2.7 on 2019-11-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_remove_status_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('name', 'phone')},
        ),
    ]
