# Generated by Django 2.2.7 on 2019-11-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_auto_20191109_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='imutable',
            field=models.BooleanField(default=False),
        ),
    ]
